### PR TITLE
Fix for updated variable name in Capybara 2.5.0

### PR DESCRIPTION
**Pull request by streetlogics**
In capybara 2.5.0, "default_wait_time" has been renamed "default_max_wait_time".  This update addresses that, and creates a hard requirement on having 2.5.0 since that variable didn't exist before that version.

### CODE REVIEW

**Comment by henning-koch** [comment]
Sorry, Spreewald needs to support Capybara 1x and 2 < 2.5. If Capybara broke an API, we need to make a version switch.

**Comment by streetlogics** [comment]
Yah, it's currently deprecated in 2.5.0, so it just throws an error message, but it's displayed quite often and very annoying when running tests with the gem installed.  I guess an alternative would be to check for the presence of the new version and use it if it's defined, otherwise fall back to the old name.

**Comment by henning-koch** [comment]
I think checking if `Capybara` responds to the new version, and using the old name as a fallback, is the best way to go.

**Comment by foobear** [comment]
Just released 1.2.13 which uses `default_max_wait_time` if available, or falls back to `default_wait_time` on older Capybaras. :rocket:

**Pull request closed without merging**
