### PR TITLE
Fix status code in Rakefile

### PR DESCRIPTION
**Pull request by FLeinzi**

### CODE REVIEW

**Comment by FLeinzi** [comment]
The job fails now as expected. The reason will be fixed in an other commit. We have to upgrade a few gems in ruby 2.6.6.
@begerdom already did this in his PR.

**Review by kratob — APPROVED** [review]
Changes are fine. But could you also take a look at the overridden `matrix:test` command? That seems completely broken to me, it neither honours its arguments (which make no sense to begin with) and it also does not set the status code. My feeling is we don't need this at all, Gemika should already provide this?

**Comment by FLeinzi** [comment]
> Changes are fine. But could you also take a look at the overridden `matrix:test` command? That seems completely broken to me, it neither honours its arguments (which make no sense to begin with)

The task uses

```ruby
Gemika::Matrix.from_ci_config.each do |row|
  run_tests(row.gemfile, row.ruby)
end
```
with
```
rows = [
  #<Gemika::Matrix::Row:0x000055b862dedb70 @gemfile="tests/rails-6_capybara-3/Gemfile", @ruby="3.0.0">,
  #<Gemika::Matrix::Row:0x000055b862dedaf8 @gemfile="Gemfile.ruby266", @ruby="2.6.6">,
  #<Gemika::Matrix::Row:0x000055b862dedaa8 @gemfile="Gemfile.ruby300", @ruby="3.0.0">
],
```
This will iterate over all rows that match the current ruby version. So for `3.0.0` the second row will be skipped. We don't need any arguments here.

> and it also does not set the status code. My feeling is we don't need this at all, Gemika should already provide this?

Gemika uses the return value of each iteration to determine if it has succeeded or not. It will then write a summary like this:
> - tests/rails-6_capybara-3/Gemfile  Ruby 3.0.0  Failed
> - Gemfile.ruby266                   Ruby 2.6.6  Skipped
> - Gemfile.ruby300                   Ruby 3.0.0  Failed
>
> Some gemfiles failed

The task will also fail then.

So we don't need to change anything here.

**Comment by kratob** [comment]
> This will iterate over all rows that match the current ruby version. So for `3.0.0` the second row will be skipped. We don't need any arguments here.

But the rake task does accept two arguments, it just ignores them.




> Gemika uses the return value of each iteration to determine if it has succeeded or not. It will then write a summary like this:

I see. I did not expect the `each` method to do anything with the return values, that's kind of unexpected. But okay.

**Comment by judithroth** [comment]
We need to overwrite the `rake matrix:tests` task because Spreewald has rspec tests and two kinds of cucumber tests: 1. for the binary, 2. for the test projects. They need to be run in different subfolders.

But I think Tobias is right - `task :tests, [:gemfile, :ruby] do |_t, args|` does not use its arguments and does not need them.

Maybe it's a different topic but I wonder about the output of `rake matrix:list`:

```
- tests/rails-6_capybara-3/Gemfile  Ruby 3.0.0  Skipped
- Gemfile.ruby266                   Ruby 2.6.6  Success
- Gemfile.ruby300                   Ruby 3.0.0  Skipped
```
This is missing the tests for our rails-4_capybara-2 test project. If we don't want to support Rails 4 and Capybara 2 any more, we should remove it completely. I am not sure we should already remove support for that?

**Comment by FLeinzi** [comment]
> Maybe it's a different topic but I wonder about the output of `rake matrix:list`:
> 
> ```
> - tests/rails-6_capybara-3/Gemfile  Ruby 3.0.0  Skipped
> - Gemfile.ruby266                   Ruby 2.6.6  Success
> - Gemfile.ruby300                   Ruby 3.0.0  Skipped
> ```
> 
> This is missing the tests for our rails-4_capybara-2 test project. If we don't want to support Rails 4 and Capybara 2 any more, we should remove it completely. I am not sure we should already remove support for that?

We don't have them in the repo anymore since 92eb62b53d3548d2a7bc8cd9ab45600602dea2a1. I also removed them in my local folder today.

**Comment by FLeinzi** [comment]
> We need to overwrite the `rake matrix:tests` task because Spreewald has rspec tests and two kinds of cucumber tests: 1. for the binary, 2. for the test projects. They need to be run in different subfolders.
> 
> But I think Tobias is right - `task :tests, [:gemfile, :ruby] do |_t, args|` does not use its arguments and does not need them.
> 

I removed the arguments here: https://github.com/makandra/spreewald/pull/186

As far as I see we don't overwrite `rake matrix:tests`, we define it ourselves. Gemika has just a `matrix:rspec` task.

**Pull request merged**
