### PR TITLE
allow absolute urls in "then I should be on..."

### PR DESCRIPTION
**Pull request by lastobelus**
to play nice with test suites that test against multiple endpoints

### CODE REVIEW

**Comment by codener** [comment]
Dear lastobelus,
thanks for your pull request. We usually do not access external pages we do not control in tests, as the tests will break whenever the page changes. Instead, we're using a step like:

```
Then /^"([^"]*)" should link to ([^"]*?)$/ do |link_label, page|
  patiently do
    link = find_link(link_label)
    link[:href].should =~ /#{Regexp.escape path_to(page)}(\?[^\/]*)?$/ # ignore trailing timestamps
  end
end
```
(This may be even simplified; took it from a bigger project.)

Would this serve your purposes?

Cheers, Dominik

**Comment by lastobelus** [comment]
I'm writing smoke/happy-path tests for a system with several moving parts.

**Comment by codener** [comment]
What about copying the step from Spreewald and customizing it to your needs? This way you can easily extend or customize it when you need another change to that step.

**Comment by codener** [comment]
Note that Spreewald 1.5.1 offers [simple step overriding](https://github.com/makandra/spreewald#overriding-steps), which should perfectly serve your needs.

**Pull request closed without merging**
